framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    session: true
    http_client: true
    rate_limiter:
        contact_form:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'
        job_application:
            policy: sliding_window
            limit: 8
            interval: '30 minutes'
        password_reset:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        disallow_search_engine_index: false
        session:
            cookie_secure: auto
            cookie_httponly: true
            cookie_samesite: lax
        php_errors:
            log: true
