framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    session: true
    http_client: true
    rate_limiter:
        contact_form:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
