twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        google_analytics_id: '%env(string:GOOGLE_ANALYTICS_MEASUREMENT_ID)%'
        app_indexable: '%env(bool:APP_INDEXABLE)%'

when@test:
    twig:
        strict_variables: true
